### ISSUE TITLE
npm run build fail 

### ISSUE THREAD

**Issue by tereaksmey123** [mrholek/coreui-free-vue-admin-template#79]
i got no idea just copy all in Vue_Full_Project to a seperate folder and npm run dev work  but after wanna build test on hosting it give me error like this.

```
$ npm run build

> @coreui/vue@1.0.12 build C:\wamp64\www\vue-admin
> node build/build.js

- building for production...C:\wamp64\www\vue-admin\node_modules\optimize-css-assets-webpack-plugin\node_modules\last-call-webpack-plugin\src\index.js:170
    compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (C:\wamp64\www\vue-admin\node_modules\optimize-css-assets-webpack-plugin\node_modules\last-call-webpack-plugin\src\index.js:170:20)
    at Compiler.apply (C:\wamp64\www\vue-admin\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\wamp64\www\vue-admin\node_modules\webpack\lib\webpack.js:33:19)
    at err (C:\wamp64\www\vue-admin\build\build.js:19:3)
    at next (C:\wamp64\www\vue-admin\node_modules\rimraf\rimraf.js:75:7)
    at CB (C:\wamp64\www\vue-admin\node_modules\rimraf\rimraf.js:111:9)
    at C:\wamp64\www\vue-admin\node_modules\rimraf\rimraf.js:137:14
    at FSReqWrap.oncomplete (fs.js:166:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/vue@1.0.12 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/vue@1.0.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Camfone\AppData\Roaming\npm-cache\_logs\2018-05-12T05_44_11_862Z-debug.log
```

this is my config
```
'use strict'
// Template version: 1.3.1
// see http://vuejs-templates.github.io/webpack for documentation.

const path = require('path')

module.exports = {
  dev: {

    // Paths
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {},

    // Various Dev Server settings
    host: 'localhost', // can be overwritten by process.env.HOST
    port: 8080, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
    autoOpenBrowser: true,
    errorOverlay: true,
    notifyOnErrors: true,
    poll: false, // https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

    // Use Eslint Loader?
    // If true, your code will be linted during bundling and
    // linting errors and warnings will be shown in the console.
    useEslint: true,
    // If true, eslint errors and warnings will also be shown in the error overlay
    // in the browser.
    showEslintErrorsInOverlay: true,

    /**
     * Source Maps
     */

    // https://webpack.js.org/configuration/devtool/#development
    devtool: 'cheap-module-eval-source-map',

    // If you have problems debugging vue-files in devtools,
    // set this to false - it *may* help
    // https://vue-loader.vuejs.org/en/options.html#cachebusting
    cacheBusting: true,

    cssSourceMap: true
  },

  build: {
    // Template for index.html
    index: path.resolve(__dirname, '../dist/index.html'),

    // Paths
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',

    /**
     * Source Maps
     */

    productionSourceMap: true,
    // https://webpack.js.org/configuration/devtool/#production
    devtool: '#source-map',

    // Gzip off by default as many popular static hosts such as
    // Surge or Netlify already gzip all static assets for you.
    // Before setting to `true`, make sure to:
    // npm install --save-dev compression-webpack-plugin
    productionGzip: false,
    productionGzipExtensions: ['js', 'css'],

    // Run the build command with an extra argument to
    // View the bundle analyzer report after build finishes:
    // `npm run build --report`
    // Set to `true` or `false` to always turn it on or off
    bundleAnalyzerReport: process.env.npm_config_report
  }
}

```
Help please Thank in advanced

**Comment by tereaksmey123** [comment]
@mrholek i found solution because your package json is webpack v3x while u set "optimize-css-assets-webpack-plugin": "^4.0.1" because it for webpack v4 only please kindly fix in your package `"optimize-css-assets-webpack-plugin": "^3.2.0",` Thank for your awesome work.
